---
# defaults file for tower

tower_webservers_group: security_group_webservers
tower_dbservers_group: security_group_dbservers

tower_inventory_hostname_variable: ec2_private_ip_address

tower_admin_password: password

tower_postgres_host: "{{groups[tower_dbservers_group][0]}}"
tower_postgres_port: 5432
tower_postgres_database: awx
tower_postgres_username: awx
tower_postgres_password: password

tower_rabbitmq_port: 5672
tower_rabbitmq_vhost: tower
tower_rabbitmq_username: tower
tower_rabbitmq_password: password
tower_rabbitmq_cookie: cookiemonster

#Needs to be true for fqdns and ip addresses
tower_rabbitmq_use_long_name: true
