---
# Tasks to install Ansible Tower

- name: Install EPEL repository
  yum:
      name: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      state: present
  become: true

- name: Install ansible
  yum:
      name: ansible
      state: present
  become: true

- name: Get tower install package
  get_url:
      url: https://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-3.1.3.tar.gz
      dest: /tmp/ansible-tower-setup-3.1.3.tar.gz

- name: Unarchive tower install package
  unarchive:
      src: /tmp/ansible-tower-setup-3.1.3.tar.gz
      dest: /tmp/
      remote_src: true

- name: Populate tower installer inventory file
  template:
      src: inventory.j2
      dest: /tmp/ansible-tower-setup-3.1.3/inventory
