---

# EC2 Cloud role stuff
vpc_name: ansible-vpc
vpc_cidr: 10.1.3.0/24
vpc_region: us-east-2
vpc_tags: "{'Name': '{{vpc_name}}'}"

vpc_private_subnet_name: ansible-private-subnet
vpc_private_subnet_cidr: 10.1.3.0/25
vpc_public_subnet_name: ansible-public-subnet
vpc_public_subnet_cidr: 10.1.3.128/25

vpc_bastion_security_group_name: ansible-bastion
vpc_webserver_security_group_name: ansible-webserver
vpc_dbserver_security_group_name: ansible-dbserver
      
# Tower role stuff
tower_webservers:
    - towerweb1
    - towerweb2
    - towerweb3

tower_dbservers:
    - towerdb1
    - towerdb2

bastion_hosts:
    - bastion1

webserver_ami: ami-0932686c
dbserver_ami: ami-0932686c
bastion_ami: ami-0932686c

web_keypair_name: redhat
db_keypair_name: redhat
bastion_keypair_name: redhat
